# Generated by Django 3.2.21 on 2023-09-07 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StoreAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 7, 9, 19, 23, 411158, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.CheckConstraint(check=models.Q(('created_at__gte', datetime.datetime(2023, 8, 31, 9, 17, 54, 202654, tzinfo=utc))), name='total_boxes_added_in_a_week'),
        ),
    ]
